name: publish to gh-pages
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Generate & Deploy
    steps:
    # Checkout your repo locally
    - uses: actions/checkout@v2

    # Deploy in Github Pages (you can use others)
    - name: deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
